export const ClassActionTypes = {
    ADD_CLASS:'ADD_CLASS',
    UPDATE_CLASS: 'UPDATE_CLASS',
    DELETE_CLASS: 'DELETE_CLASS', //Only deletable if no student added
    SET_CLASSES: 'SET_CLASSES',
    SELECTED_CLASS: 'SELECTED_CLASS',

    ADD_CLASS_FEES: 'ADD_CLASS_FEES',
    UPDATE_CLASS_FEES: 'UPDATE_CLASS_FEES',
    SET_CLASS_FEES: 'SET_CLASS_FEES',
    SELECTED_CLASS_FEES: 'SELECTED_CLASS_FEES',

    ADD_CLASS_TEACHER: 'ADD_CLASS_TEACHER',
    UPDATE_CLASS_TEACHER: 'UPDATE_CLASS_TEACHER',
    SET_CLASS_TEACHER: 'SET_CLASS_TEACHER',
    SELECTED_CLASS_TEACHER: 'SELECTED_CLASS_TEACHER',

    ADD_CLASS_SUBJECT: 'ADD_CLASS_SUBJECT',
    UPDATE_CLASS_SUBJECT: 'UPDATE_CLASS_SUBJECT',
    SET_CLASS_SUBJECTS: 'SET_CLASS_SUBJECTS',
    SELECTED_CLASS_SUBJECT: 'SELECTED_CLASS_SUBJECT',
}