export const PositionActionTypes = {
    ADD_POSITION:'ADD_POSITION',
    UPDATE_POSITION:'UPDATE_POSITION',
    SET_POSITIONS:'SET_POSITIONS',
    SELECTED_POSITION:'SELECTED_POSITION',
    DELETE_POSITION:'DELETE_POSITION',
}