export const SchoolActionTypes = {
    ADD_SCHOOL_INFORMATION:'ADD_SCHOOL_INFORMATION',
    SET_SCHOOL_INFORMATION: 'SET_SCHOOL_INFORMATION',
    SET_SCHOOL_BANK_INFORMATION: 'SET_SCHOOL_BANK_INFORMATION',
    UPDATE_SCHOOL_INFORMATION: 'UPDATE_SCHOOL_INFORMATION',
}