export const SessionActionTypes = {
    //Managing School Session
    ADD_SCHOOL_SESSION: 'ADD_SCHOOL_SESSION',
    UPDATE_SCHOOL_SESSION: 'UPDATE_SCHOOL_SESSION',
    DELETE_SCHOOL_SESSION: 'DELETE_SCHOOL_SESSION',
    SET_SCHOOL_SESSIONS: 'SET_SCHOOL_SESSIONS',
    SELECTED_SCHOOL_SESSION: 'SELECTED_SCHOOL_SESSION',
}