export const StaffActionTypes = {
    ADD_STAFF:'ADD_STAFF',
    ADD_MULTIPLE_STAFF: 'ADD_MULTIPLE_STAFF',
    ADD_STAFF_SALARY_INFORMATION: '',
    SET_STAFF: 'SET_STAFF_INFORMATION',
    SELECTED_STAFF: 'SELECTED_STAFF',
    UPDATE_STAFF: 'UPDATE_STAFF',
    CHANGE_STAFF_STATUS: 'CHANGE_STAFF_STATUS',
    SET_STAFF_SALARY_INFORMATION: 'SET_STAFF_SALARY_INFORMATION',
    SELECTED_STAFF_SALARY_INFORMATION: 'SELECTED_STAFF_SALARY_INFORMATION',
}