export const SubjectActionTypes = {
    ADD_SUBJECT: 'ADD_SUBJECT',
    SET_SUBJECTS: 'SET_SUBJECTS',
    SELECTED_SUBJECT: 'SELECTED_SUBJECT',
    UPDATE_SUBJECT: 'UPDATE_SUBJECT',
    DELETE_SUBJECT: 'DELETE_SUBJECT',
}